'use client';

import React, { useState } from 'react';
import CodeViewer from './CodeViewer';

interface Design {
  style: string;
  styleName: string;
  framework: string;
  frameworkLabel: string;
  ext: string;
  code: string;
  previewHtml?: string;
  previewType?: 'html' | 'sandpack';
}

interface Stats { headings: number; paragraphs: number; listItems: number; tags: number; sections: number; }

interface Props {
  designs: Design[];
  websiteUrl: string;
  pageTitle: string;
  screenshotBase64?: string;
  stats?: Stats;
  onReset: () => void;
  isStreaming?: boolean;
  pendingStyles?: string[];
}

const STYLE_META: Record<string, { gradient: string; badge: string }> = {
  minimal:  { gradient: 'from-slate-100 to-white',               badge: 'bg-slate-100 text-slate-700' },
  bold:     { gradient: 'from-slate-900 to-slate-800',           badge: 'bg-blue-500/20 text-blue-300' },
  colorful: { gradient: 'from-pink-500 via-purple-500 to-indigo-500', badge: 'bg-purple-100 text-purple-700' },
  custom:   { gradient: 'from-amber-400 via-orange-500 to-rose-500',  badge: 'bg-amber-100 text-amber-700' },
  custom_1: { gradient: 'from-amber-400 via-orange-500 to-rose-500',  badge: 'bg-amber-100 text-amber-700' },
  custom_2: { gradient: 'from-emerald-400 via-teal-500 to-cyan-500',  badge: 'bg-emerald-100 text-emerald-700' },
  custom_3: { gradient: 'from-rose-400 via-red-500 to-orange-500',    badge: 'bg-rose-100 text-rose-700' },
};
const FALLBACK_META = STYLE_META.minimal;

function getExt(framework: string) {
  if (framework === 'react' || framework === 'nextjs') return 'jsx';
  if (framework === 'vue') return 'vue';
  if (framework === 'angular') return 'ts';
  return 'html';
}

function fwLabel(framework: string) {
  const m: Record<string, string> = { html: 'HTML/CSS/JS', react: 'React JSX', nextjs: 'Next.js', vue: 'Vue 3', angular: 'Angular' };
  return m[framework] ?? framework;
}

function fwColor(framework: string) {
  const m: Record<string, string> = { html: '#e34c26', react: '#61dafb', nextjs: '#ffffff', vue: '#42b883', angular: '#dd0031' };
  return m[framework] ?? '#6366f1';
}

// ──────────────────────────────────────────────────────────────────────────
// Preview area — always uses previewHtml iframe (instant, no CDN needed)
// previewHtml is always plain HTML generated by backend for ALL frameworks
// ──────────────────────────────────────────────────────────────────────────
const LivePreview = ({
  design,
  height = '100%',
}: {
  design: Design;
  height?: string | number;
}) => (
  <iframe
    srcDoc={design.previewHtml || design.code || ''}
    style={{ width: '100%', height, border: 'none', display: 'block' }}
    sandbox="allow-scripts allow-same-origin"
    title={design.styleName || 'preview'}
  />
);

// ──────────────────────────────────────────────────────────────────────────
// Full-screen modal
// ──────────────────────────────────────────────────────────────────────────
const PreviewModal = ({ design, onClose }: { design: Design; onClose: () => void }) => {
  const [tab, setTab] = useState<'preview' | 'code'>('preview');
  const code = design.code || design.previewHtml || '';
  const ext = getExt(design.framework);
  const color = fwColor(design.framework);

  const handleDownload = () => {
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `design-${design.style}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: 'rgba(0,0,0,0.92)',
        display: 'flex', flexDirection: 'column',
        backdropFilter: 'blur(8px)',
      }}
    >
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '12px 20px',
        background: '#0d1117',
        borderBottom: '1px solid rgba(255,255,255,0.08)',
        flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontWeight: 700, color: '#e2e8f0', fontSize: 15 }}>{design.styleName}</span>
          <span style={{
            display: 'inline-flex', alignItems: 'center', gap: 5,
            padding: '3px 10px', borderRadius: 20,
            background: 'rgba(99,102,241,0.15)',
            border: '1px solid rgba(99,102,241,0.3)',
            fontSize: 11, fontWeight: 700, color,
          }}>
            <span style={{ width: 6, height: 6, borderRadius: '50%', background: color, display: 'inline-block' }} />
            {fwLabel(design.framework)}
          </span>
        </div>

        {/* Tabs + actions */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          {(['preview', 'code'] as const).map(t => (
            <button key={t} onClick={() => setTab(t)} style={{
              padding: '5px 14px', borderRadius: 8, fontSize: 12, fontWeight: 700,
              cursor: 'pointer', border: 'none', fontFamily: 'inherit',
              background: tab === t ? 'rgba(99,102,241,0.25)' : 'transparent',
              color: tab === t ? '#a5b4fc' : '#64748b',
              transition: 'all 0.15s',
            }}>
              {t === 'preview' ? '👁 Preview' : '{ } Code'}
            </button>
          ))}
          <div style={{ width: 1, height: 20, background: 'rgba(255,255,255,0.1)', margin: '0 4px' }} />
          <button onClick={handleDownload} style={{
            display: 'flex', alignItems: 'center', gap: 5,
            padding: '5px 12px', borderRadius: 8, fontSize: 12, fontWeight: 600,
            background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.12)',
            color: '#94a3b8', cursor: 'pointer', fontFamily: 'inherit',
          }}>
            <svg width="13" height="13" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download .{ext}
          </button>
          <button onClick={onClose} style={{
            width: 32, height: 32, borderRadius: 8, border: '1px solid rgba(255,255,255,0.12)',
            background: 'rgba(255,255,255,0.06)', color: '#94a3b8',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            cursor: 'pointer', fontSize: 16, fontFamily: 'inherit',
          }}>✕</button>
        </div>
      </div>

      {/* Body */}
      <div style={{ flex: 1, overflow: 'hidden' }}>
        {tab === 'preview' ? (
          <LivePreview design={design} height="100%" />
        ) : (
          <CodeViewer code={code} framework={design.framework} filename={`design-${design.style}.${ext}`} height="100%" />
        )}
      </div>
    </div>
  );
};

// ──────────────────────────────────────────────────────────────────────────
// Design Card
// ──────────────────────────────────────────────────────────────────────────
const DesignCard = ({ design, index, onClick }: { design: Design; index: number; onClick: () => void }) => {
  const [cardTab, setCardTab] = useState<'preview' | 'code'>('preview');
  const [copied, setCopied] = useState(false);
  const meta = STYLE_META[design.style] || FALLBACK_META;
  const color = fwColor(design.framework);
  const code = design.code || design.previewHtml || '';

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation();
    await navigator.clipboard.writeText(code).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div
      style={{
        background: '#fff',
        borderRadius: 16,
        overflow: 'hidden',
        boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
        border: '1.5px solid #e2e8f0',
        display: 'flex', flexDirection: 'column',
        animation: `slideUp 0.4s ${index * 0.08}s both`,
        transition: 'transform 0.2s, box-shadow 0.2s',
      }}
      onMouseEnter={e => {
        (e.currentTarget as HTMLDivElement).style.transform = 'translateY(-4px)';
        (e.currentTarget as HTMLDivElement).style.boxShadow = '0 12px 40px rgba(0,0,0,0.15)';
      }}
      onMouseLeave={e => {
        (e.currentTarget as HTMLDivElement).style.transform = 'translateY(0)';
        (e.currentTarget as HTMLDivElement).style.boxShadow = '0 4px 20px rgba(0,0,0,0.08)';
      }}
    >
      {/* Card tab bar */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '8px 12px',
        background: '#f8fafc',
        borderBottom: '1px solid #e2e8f0',
      }}>
        <div style={{ display: 'flex', gap: 4 }}>
          {(['preview', 'code'] as const).map(t => (
            <button key={t} onClick={e => { e.stopPropagation(); setCardTab(t); }} style={{
              padding: '3px 10px', borderRadius: 6, fontSize: 11, fontWeight: 700,
              cursor: 'pointer', border: 'none', fontFamily: 'inherit',
              background: cardTab === t ? '#e0e7ff' : 'transparent',
              color: cardTab === t ? '#4f46e5' : '#94a3b8',
              transition: 'all 0.15s',
            }}>
              {t === 'preview' ? 'Preview' : 'Code'}
            </button>
          ))}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{
            display: 'inline-flex', alignItems: 'center', gap: 4,
            padding: '2px 8px', borderRadius: 20,
            background: 'rgba(99,102,241,0.08)',
            fontSize: 10, fontWeight: 700, color,
          }}>
            <span style={{ width: 5, height: 5, borderRadius: '50%', background: color, display: 'inline-block' }} />
            {fwLabel(design.framework)}
          </span>
          <button onClick={handleCopy} style={{
            display: 'flex', alignItems: 'center', gap: 4,
            padding: '2px 8px', borderRadius: 6, fontSize: 10, fontWeight: 700,
            background: copied ? 'rgba(16,185,129,0.1)' : 'rgba(99,102,241,0.08)',
            border: `1px solid ${copied ? 'rgba(16,185,129,0.3)' : 'rgba(99,102,241,0.2)'}`,
            color: copied ? '#10b981' : '#6366f1', cursor: 'pointer', fontFamily: 'inherit',
          }}>
            {copied ? '✓ Copied' : 'Copy'}
          </button>
        </div>
      </div>

      {/* Card body — Preview or Code */}
      <div style={{ height: 220, position: 'relative', overflow: 'hidden', cursor: cardTab === 'preview' ? 'pointer' : 'default' }}
        onClick={cardTab === 'preview' ? onClick : undefined}
      >
        {cardTab === 'preview' ? (
          <>
            {/* Scaled preview — always use previewHtml iframe for fast card thumbnails */}
            <iframe
              srcDoc={design.previewHtml || code}
              style={{
                position: 'absolute', top: 0, left: 0, border: 'none',
                width: '1400px', height: '900px',
                transform: 'scale(0.245)', transformOrigin: 'top left',
                pointerEvents: 'none',
              }}
              sandbox="allow-scripts allow-same-origin"
              title={design.styleName}
            />
            {/* Click overlay */}
            <div
              style={{
                position: 'absolute', inset: 0,
                background: 'transparent',
                display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
                paddingBottom: 12, opacity: 0, transition: 'opacity 0.2s',
              }}
              className="card-expand-overlay"
            >
              <span style={{
                background: 'rgba(15,23,42,0.85)', color: '#fff',
                padding: '5px 14px', borderRadius: 20, fontSize: 11, fontWeight: 700,
              }}>Click to expand ↗</span>
            </div>
          </>
        ) : (
          <div style={{ height: '100%', overflow: 'hidden', background: '#0d1117' }}>
            <pre style={{
              margin: 0, padding: '12px 14px',
              color: '#a5b4fc', fontSize: 10.5,
              fontFamily: '"JetBrains Mono", monospace',
              lineHeight: 1.6, overflow: 'auto', height: '100%',
              whiteSpace: 'pre-wrap', wordBreak: 'break-all',
            }}>
              {code.slice(0, 2000)}{code.length > 2000 ? '\n\n... (click expand to see full code)' : ''}
            </pre>
          </div>
        )}
      </div>

      {/* Card footer */}
      <div style={{ padding: '10px 14px', borderTop: '1px solid #f1f5f9' }}>
        <p style={{ fontWeight: 700, fontSize: 13, color: '#1e293b', margin: 0 }}>{design.styleName}</p>
        <p style={{ fontSize: 11, color: '#94a3b8', margin: '2px 0 0' }}>{fwLabel(design.framework)} · Click preview to expand</p>
      </div>
    </div>
  );
};

// ──────────────────────────────────────────────────────────────────────────
// Skeleton Card
// ──────────────────────────────────────────────────────────────────────────
const SkeletonCard = ({ style }: { style: string }) => {
  const meta = STYLE_META[style] || FALLBACK_META;
  return (
    <div style={{
      borderRadius: 16, overflow: 'hidden',
      boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
      border: '1.5px solid #e2e8f0',
    }}>
      <div style={{
        height: 220, position: 'relative',
        background: 'linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%)',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute', inset: 0,
          background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.6) 50%, transparent 100%)',
          backgroundSize: '200% 100%',
          animation: 'shimmer 1.5s infinite',
        }} />
        <div style={{
          position: 'absolute', inset: 0,
          display: 'flex', flexDirection: 'column',
          alignItems: 'center', justifyContent: 'center', gap: 10,
        }}>
          <div style={{
            width: 28, height: 28,
            border: '3px solid rgba(99,102,241,0.25)',
            borderTop: '3px solid #6366f1',
            borderRadius: '50%',
            animation: 'spin 0.8s linear infinite',
          }} />
          <p style={{ color: '#94a3b8', fontSize: 12, margin: 0 }}>Generating…</p>
        </div>
      </div>
      <div style={{ padding: '10px 14px', background: '#fff' }}>
        <div style={{ height: 12, background: '#e2e8f0', borderRadius: 6, width: '60%', animation: 'pulse 1.5s infinite' }} />
        <div style={{ height: 10, background: '#f1f5f9', borderRadius: 6, width: '40%', marginTop: 6, animation: 'pulse 1.5s infinite' }} />
      </div>
      <style>{`
        @keyframes shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}
        @keyframes spin{to{transform:rotate(360deg)}}
        @keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}
        @keyframes slideUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
        .card-expand-overlay:hover{opacity:1!important}
      `}</style>
    </div>
  );
};

// ──────────────────────────────────────────────────────────────────────────
// Main Results Component
// ──────────────────────────────────────────────────────────────────────────
const WebsiteRedesignerResults: React.FC<Props> = ({
  designs, websiteUrl, pageTitle, screenshotBase64, stats, onReset, isStreaming, pendingStyles = [],
}) => {
  const [openDesign, setOpenDesign] = useState<Design | null>(null);

  const hostname = (() => { try { return new URL(websiteUrl).hostname; } catch { return websiteUrl; } })();

  return (
    <>
      <style>{`
        @keyframes slideUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
        @keyframes shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}
        @keyframes spin{to{transform:rotate(360deg)}}
        @keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}
      `}</style>

      {openDesign && <PreviewModal design={openDesign} onClose={() => setOpenDesign(null)} />}

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '32px 24px' }}>

        {/* ── Header ── */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
            {screenshotBase64 && (
              <img
                src={`data:image/jpeg;base64,${screenshotBase64}`}
                style={{ width: 64, height: 44, objectFit: 'cover', borderRadius: 8, border: '1.5px solid #e2e8f0' }}
                alt="screenshot"
              />
            )}
            <div>
              <p style={{ margin: 0, fontSize: 12, color: '#94a3b8', fontFamily: 'monospace' }}>{hostname}</p>
              <h2 style={{ margin: '2px 0 0', fontSize: 22, fontWeight: 800, color: '#0f172a' }}>
                {pageTitle || hostname}
              </h2>
              <p style={{ margin: '2px 0 0', fontSize: 12, color: '#64748b' }}>
                {isStreaming
                  ? `${designs.length} ready · ${pendingStyles.length} generating…`
                  : `${designs.length} design${designs.length !== 1 ? 's' : ''} generated`}
              </p>
            </div>
          </div>

          <button
            onClick={onReset}
            style={{
              display: 'flex', alignItems: 'center', gap: 6,
              padding: '8px 16px', borderRadius: 10,
              border: '1.5px solid #e2e8f0', background: '#fff',
              fontSize: 13, fontWeight: 700, color: '#475569',
              cursor: 'pointer', fontFamily: 'inherit',
              transition: 'all 0.15s',
            }}
          >
            ← New Redesign
          </button>
        </div>

        {/* ── Stats ── */}
        {stats && (
          <div style={{
            display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 28,
            padding: '12px 16px', background: '#f8fafc', borderRadius: 12,
            border: '1px solid #e2e8f0',
          }}>
            {[
              { label: 'Headings', val: stats.headings },
              { label: 'Paragraphs', val: stats.paragraphs },
              { label: 'List Items', val: stats.listItems },
              { label: 'Badges', val: stats.tags },
              { label: 'Sections', val: stats.sections },
            ].map(s => (
              <div key={s.label} style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '4px 12px', borderRadius: 20,
                background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.18)',
              }}>
                <span style={{ fontWeight: 800, fontSize: 13, color: '#4f46e5' }}>{s.val}</span>
                <span style={{ fontSize: 11, color: '#64748b' }}>{s.label}</span>
              </div>
            ))}
          </div>
        )}

        {/* ── Grid ── */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
          gap: 24,
        }}>
          {designs.map((design, i) => (
            <DesignCard
              key={design.style}
              design={design}
              index={i}
              onClick={() => setOpenDesign(design)}
            />
          ))}
          {pendingStyles.map(s => <SkeletonCard key={s} style={s} />)}
        </div>

      </div>
    </>
  );
};

export default WebsiteRedesignerResults;