'use client';

import React, { useState } from 'react';
import { api } from '@/lib/api';

interface PRCreatorProps {
  sessionId: string;
  acceptedFiles: string[];
  repoFullName: string;
  onBack: () => void;
}

interface PRResult { number: number; url: string; title: string; branch: string; }

export default function PRCreator({ sessionId, acceptedFiles, repoFullName, onBack }: PRCreatorProps) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const randSuffix = Math.random().toString(36).slice(2, 6);

  const [branchName, setBranchName] = useState(`flowfinder/a11y-fixes-${dateStr}-${randSuffix}`);
  const [prTitle, setPrTitle] = useState('♿ FlowFinder: Accessibility Fixes');
  const [prBody, setPrBody] = useState(
    `## ♿ FlowFinder — Accessibility Fixes\n\nThis PR was automatically generated by [FlowFinder](https://flowfinder.app) to fix accessibility issues.\n\n### Files Changed\n${acceptedFiles.map(f => `- \`${f}\``).join('\n')}\n\n### References\n- [WCAG 2.1 Guidelines](https://www.w3.org/WAI/WCAG21/quickref/)\n\n---\n*Review each change carefully before merging.*`
  );
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [pr, setPr] = useState<PRResult | null>(null);

  const handleCreate = async () => {
    setCreating(true);
    setError(null);
    try {
      const result = await api.post<any>(`/api/fixes/${sessionId}/create-pr`, {
        acceptedFiles,
        branchName,
        prTitle,
        prBody,
      });
      setPr(result.pr);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setCreating(false);
    }
  };

  // ── Success state ──────────────────────────────────────────────────────────
  if (pr) {
    return (
      <div style={{ maxWidth: '600px', margin: '0 auto', padding: '40px 20px', textAlign: 'center', fontFamily: 'Inter, sans-serif' }}>
        <div style={{ width: '72px', height: '72px', borderRadius: '50%', background: 'linear-gradient(135deg,#22c55e,#16a34a)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px', boxShadow: '0 8px 30px rgba(34,197,94,0.3)' }}>
          <svg width="36" height="36" fill="none" stroke="#fff" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7"/></svg>
        </div>
        <h2 style={{ fontSize: '26px', fontWeight: 800, color: '#0f172a', margin: '0 0 8px' }}>PR Created! 🎉</h2>
        <p style={{ color: '#64748b', fontSize: '15px', marginBottom: '28px' }}>
          Pull request #{pr.number} has been opened on <strong>{repoFullName}</strong>
        </p>

        <div style={{ background: '#f8fafc', border: '1.5px solid #e2e8f0', borderRadius: '16px', padding: '20px', marginBottom: '24px', textAlign: 'left' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px' }}>
            <div style={{ width: '40px', height: '40px', background: '#1e293b', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <svg width="22" height="22" fill="#fff" viewBox="0 0 24 24"><path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/></svg>
            </div>
            <div style={{ minWidth: 0 }}>
              <p style={{ margin: '0 0 4px', fontSize: '16px', fontWeight: 700, color: '#0f172a' }}>{pr.title}</p>
              <p style={{ margin: '0 0 8px', fontSize: '13px', color: '#64748b' }}>{repoFullName} · #{pr.number}</p>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ padding: '3px 10px', background: '#f0fdf4', color: '#15803d', fontSize: '12px', fontWeight: 700, borderRadius: '20px', border: '1px solid #86efac' }}>Open</span>
                <code style={{ fontSize: '12px', color: '#475569', background: '#f1f5f9', padding: '2px 8px', borderRadius: '6px', fontFamily: 'JetBrains Mono, monospace' }}>{pr.branch}</code>
              </div>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '12px', justifyContent: 'center' }}>
          <a
            href={pr.url}
            target="_blank"
            rel="noopener noreferrer"
            style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '12px 24px', background: 'linear-gradient(135deg,#1e293b,#334155)', color: '#fff', textDecoration: 'none', borderRadius: '12px', fontSize: '14px', fontWeight: 700, boxShadow: '0 4px 14px rgba(0,0,0,0.15)' }}
          >
            <svg width="16" height="16" fill="#fff" viewBox="0 0 24 24"><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6M15 3h6v6M10 14L21 3"/></svg>
            View on GitHub
          </a>
          <button
            onClick={onBack}
            style={{ padding: '12px 24px', background: '#f1f5f9', border: 'none', borderRadius: '12px', cursor: 'pointer', fontSize: '14px', fontWeight: 600, color: '#475569' }}
          >
            Back to Diffs
          </button>
        </div>
      </div>
    );
  }

  // ── PR form ────────────────────────────────────────────────────────────────
  return (
    <div style={{ maxWidth: '680px', margin: '0 auto', fontFamily: 'Inter, sans-serif' }}>
      <div style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '6px' }}>
          <button onClick={onBack} style={{ padding: '8px 14px', background: '#f1f5f9', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '13px', fontWeight: 600, color: '#475569' }}>
            ← Back
          </button>
          <h2 style={{ fontSize: '22px', fontWeight: 800, color: '#0f172a', margin: 0 }}>Create Pull Request</h2>
        </div>
        <p style={{ color: '#64748b', fontSize: '14px', margin: 0 }}>
          {acceptedFiles.length} file{acceptedFiles.length !== 1 ? 's' : ''} will be committed to <strong>{repoFullName}</strong>
        </p>
      </div>

      {/* Files summary */}
      <div style={{ background: '#f8fafc', border: '1.5px solid #e2e8f0', borderRadius: '14px', padding: '16px 20px', marginBottom: '20px' }}>
        <p style={{ margin: '0 0 10px', fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase' }}>Files to commit</p>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
          {acceptedFiles.map(f => (
            <div key={f} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 10px', background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: '8px' }}>
              <svg width="12" height="12" fill="none" stroke="#22c55e" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7"/></svg>
              <code style={{ fontSize: '12px', color: '#475569', fontFamily: 'JetBrains Mono, monospace' }}>{f.split('/').pop()}</code>
            </div>
          ))}
        </div>
      </div>

      {/* Form fields */}
      <div style={{ background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: '14px', padding: '24px', display: 'flex', flexDirection: 'column', gap: '18px' }}>
        {/* Branch name */}
        <div>
          <label style={{ display: 'block', fontSize: '13px', fontWeight: 700, color: '#374151', marginBottom: '8px' }}>
            Branch Name
          </label>
          <input
            value={branchName}
            onChange={e => setBranchName(e.target.value)}
            style={{ width: '100%', padding: '10px 14px', border: '2px solid #e2e8f0', borderRadius: '10px', fontSize: '13px', color: '#0f172a', fontFamily: 'JetBrains Mono, monospace', outline: 'none', boxSizing: 'border-box' }}
          />
          <p style={{ margin: '6px 0 0', fontSize: '12px', color: '#94a3b8' }}>Auto-generated. Edit if needed.</p>
        </div>

        {/* PR Title */}
        <div>
          <label style={{ display: 'block', fontSize: '13px', fontWeight: 700, color: '#374151', marginBottom: '8px' }}>PR Title</label>
          <input
            value={prTitle}
            onChange={e => setPrTitle(e.target.value)}
            style={{ width: '100%', padding: '10px 14px', border: '2px solid #e2e8f0', borderRadius: '10px', fontSize: '14px', color: '#0f172a', outline: 'none', boxSizing: 'border-box', fontFamily: 'Inter, sans-serif' }}
          />
        </div>

        {/* PR Body */}
        <div>
          <label style={{ display: 'block', fontSize: '13px', fontWeight: 700, color: '#374151', marginBottom: '8px' }}>PR Description</label>
          <textarea
            value={prBody}
            onChange={e => setPrBody(e.target.value)}
            rows={8}
            style={{ width: '100%', padding: '12px 14px', border: '2px solid #e2e8f0', borderRadius: '10px', fontSize: '13px', color: '#0f172a', outline: 'none', resize: 'vertical', fontFamily: 'JetBrains Mono, monospace', lineHeight: 1.6, boxSizing: 'border-box' }}
          />
        </div>

        {/* Error */}
        {error && (
          <div style={{ padding: '12px 16px', background: '#fef2f2', border: '1.5px solid #fecaca', borderRadius: '10px', fontSize: '13px', color: '#b91c1c' }}>
            {error}
          </div>
        )}

        {/* Submit */}
        <button
          onClick={handleCreate}
          disabled={creating}
          style={{ padding: '14px', background: creating ? '#e2e8f0' : 'linear-gradient(135deg,#1e293b,#334155)', border: 'none', borderRadius: '12px', cursor: creating ? 'not-allowed' : 'pointer', color: creating ? '#94a3b8' : '#fff', fontSize: '15px', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', boxShadow: creating ? 'none' : '0 4px 16px rgba(0,0,0,0.15)' }}
        >
          {creating ? (
            <>
              <svg style={{ animation: 'spin 1s linear infinite' }} width="18" height="18" fill="none" viewBox="0 0 24 24"><circle style={{ opacity: 0.25 }} cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path style={{ opacity: 0.75 }} fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
              Creating pull request...
            </>
          ) : (
            <>
              <svg width="18" height="18" fill="#fff" viewBox="0 0 24 24"><path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/></svg>
              Create Pull Request
            </>
          )}
        </button>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
